sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
env:
  - CHAINER_VERSION="==3.1.0" ONNX_VERSION="git+git://github.com/onnx/onnx.git@a8bd1facd321ea52f0a6f88600138606711b7a96"
  - CHAINER_VERSION="==4.0.0b1" ONNX_VERSION="git+git://github.com/onnx/onnx.git@a8bd1facd321ea52f0a6f88600138606711b7a96"
notifications:
  email: false

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda install protobuf
  - hash -r
  - CFLAGS="-I$HOME/miniconda/include" pip install $ONNX_VERSION
  - pip install "chainer$CHAINER_VERSION"
  - pip install -e .

script:
  - pwd
  - pip install flake8
  - pip install hacking
  - pip install autopep8
  - pip install mock
  - pip install pytest
  - flake8 .
  - autopep8 -r -d . | tee check_autopep8
  - test ! -s check_autopep8
  - py.test .